import type { Journey, JourneyKind, JourneyStep, TitleSummary } from "@slate/shared";

/**
 * Assembles a Journey from a franchise's real, release-ordered entries plus
 * the set of titles the user has already completed.
 *
 * The `reason` on each step is deliberately factual — release position,
 * franchise membership, target status. Slate will not assert "this sets up
 * the villain" or similar plot claims it cannot source, which is also why
 * journeys are built from provider franchise data rather than written by
 * hand or generated by the model.
 */
export function buildJourney(params: {
  id: string;
  name: string;
  kind: JourneyKind;
  source: "tmdb" | "igdb";
  parts: TitleSummary[];
  completedTitleIds: Set<string>;
  targetTitleId?: string;
}): Journey {
  const { id, name, kind, source, parts, completedTitleIds, targetTitleId } = params;

  const verb = kind === "PLAY" ? "Play" : "Watch";
  let nextAssigned = false;

  const steps: JourneyStep[] = parts.map((title, index) => {
    const completed = completedTitleIds.has(title.id);
    const isTarget = targetTitleId !== undefined && title.id === targetTitleId;

    let state: JourneyStep["state"];
    if (isTarget) {
      state = "TARGET";
    } else if (completed) {
      state = "COMPLETED";
    } else if (!nextAssigned) {
      state = "NEXT";
      nextAssigned = true;
    } else {
      state = "UPCOMING";
    }

    const year = title.releaseWindow.date ? new Date(title.releaseWindow.date).getUTCFullYear() : null;
    const reason = isTarget
      ? `The title you're building toward.`
      : `${verb} #${index + 1} in ${name}${year ? ` · released ${year}` : ""}.`;

    return { position: index + 1, title, state, reason, completed };
  });

  const completedCount = steps.filter((s) => s.completed).length;
  const nextStep = steps.find((s) => s.state === "NEXT") ?? null;

  return {
    id,
    kind,
    name,
    mediaType: parts[0]?.mediaType ?? (kind === "PLAY" ? "game" : "movie"),
    target: targetTitleId ? parts.find((p) => p.id === targetTitleId) : undefined,
    steps,
    completedCount,
    totalCount: steps.length,
    nextStep,
    source,
  };
}
