/**
 * Shared primitives for every VEO domain entity.
 */

/** Stable identifier. VEO uses UUID v4 generated by Postgres (`gen_random_uuid()`). */
export type UUID = string;

/** ISO-8601 timestamp string, as returned by Supabase/PostgREST. */
export type ISODateString = string;

/** Fields every persisted entity carries. */
export interface Timestamped {
  readonly createdAt: ISODateString;
  readonly updatedAt: ISODateString;
}

/** Free-form provider/domain metadata. Never used for authorization decisions. */
export type Metadata = Readonly<Record<string, unknown>>;

/**
 * Knowledge domains VEO is built to serve.
 *
 * This list is a *registry*, not a closed union that new domains must fight.
 * `KnowledgeDomain` stays assignable from any string so that adding a domain is
 * a data change, not a refactor of the core type system — while known domains
 * still autocomplete.
 */
export const KNOWLEDGE_DOMAINS = [
  'anatomy',
  'health_sciences',
  'engineering',
  'chemistry',
  'physics',
  'architecture',
  'computing',
  'earth_sciences',
  'astrophysics',
] as const;

export type KnownKnowledgeDomain = (typeof KNOWLEDGE_DOMAINS)[number];

export type KnowledgeDomain = KnownKnowledgeDomain | (string & {});

export function isKnownKnowledgeDomain(value: string): value is KnownKnowledgeDomain {
  return (KNOWLEDGE_DOMAINS as readonly string[]).includes(value);
}

/** Publication lifecycle shared by authored content. */
export const PUBLICATION_STATUSES = ['draft', 'published', 'archived'] as const;
export type PublicationStatus = (typeof PUBLICATION_STATUSES)[number];

/** Cursor-paginated collection returned by list endpoints. */
export interface Page<T> {
  readonly items: readonly T[];
  readonly nextCursor: string | null;
  readonly total: number | null;
}
